
#include "TileBag.h"
#include <iostream>

TileBag::TileBag() {
    tileBag = new LinkedList();
    random = 0;
    // Seed used for randomness and shuffling tilebag
    srand(time(0));
    makeBag();
}

TileBag::TileBag(LinkedList* loadedTileBag) {
    tileBag = loadedTileBag;
    random = 0;
}

TileBag::~TileBag() {
    delete tileBag;
}

/*
 * Function used to create tiles based on the characteristics of a tile.
 */
void TileBag::createTiles() {
    for (int i = 0; i < PART_LENGTH; i++) {
        for (int j = 0; j < PART_LENGTH; j++) {
            Tile* tile = new Tile(colours[i], shapes[j]);
            sortMethod(tile);
        }
    }
}

/*
 * Function first has two sets of tiles(36 tiles each) be created and randomly
 * sorted through the bag, before having them be shuffled thoroughly through
 * a shuffle method.
 */
void TileBag::makeBag() {
    int create = 0;
    int shuffle = 0;

    while (create < MAX_CREATE) {
        createTiles();
        create++;
    }

    while (shuffle < MAX_SHUFFLE) {
        shuffleBag();
        shuffle++;
    }
}

/*
 * Function to sort tiles depending on the number that is generated by the
 * random() function.
 */
void TileBag::sortMethod(Tile* tile) {
    random = rand() % MAX_CHOICE;
    addRandomTile(random, tile);
}

/*
 * Function shuffles only first half of the tiles to either the middle or the end
 * of the linked list(implemented through the addRandomTile function).
 */
void TileBag::shuffleBag() {
    int counter = 0;

    while (counter < tileBag->size()/2) {
        random = rand() % MAX_CHOICE_2;
        
        Colour nColour = getFront()->getColour();
        Shape nShape = getFront()->getShape();
        
        Tile* getTile = new Tile(nColour, nShape);

        addRandomTile(random, getTile);

        tileBag->deleteFront();

        counter++;
    }
}

/*
 * Places the tile within the linked list of the tile bag based on the random
 * parameter parsed through to the function.
 * If 0: Adds tile to the middle of the linked list
 * If 1: Adds tile to the end of the linked list
 * If 2: Adds tile to the front of the linked list
 */
void TileBag::addRandomTile(int random, Tile* tile) {
    Colour nColour = tile->getColour();
    Shape nShape = tile->getShape();
    
    Tile* nTile = new Tile(nColour, nShape);
    
    if (random == 0) {
        tileBag->addMid(nTile);
    } else if (random == 1) {
        tileBag->addEnd(nTile);
    } else if (random == 2) {
        tileBag->addFront(nTile);
    }
}

/*
 * Function used to debug if tiles were correctly made in tile
 * i.e: No more than two tiles throughout the game state
 */
void TileBag::showBag() {
    std::cout << "--------" << std::endl;
    std::cout << "Tiles currently in bag:" << "\n" << std::endl;

    for (int i = 0; i < tileBag->size(); i++) {
        std::cout << tileBag->get(i)->getColour();
        std::cout << tileBag->get(i)->getShape();

        if ((i % 8) == 7) {
            std::cout << std::endl;
        } else {
            std::cout << " ";
        }
    }

    std::cout << std::endl << "--------" << std::endl;
}

/*
 * Returns the front of the linked list which is at index 0.
 */
Tile* TileBag::getFront() {
    return getTileBag()->get(0);
}

/*
 * Returns the size of the linked list through the size() function.
 */
int TileBag::size() {
    return getTileBag()->size();
}

/*
 * Returns access to the linked list of the tile bag
 */
LinkedList* TileBag::getTileBag() {
    return tileBag;
}
